# Generated by Django 3.2.3 on 2021-10-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt_date', models.CharField(default='Dec 31, 2020, 14:00', max_length=64)),
                ('exerpt_text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=64)),
                ('book', models.CharField(max_length=64)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user_excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userexcerpt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
