# Generated by Django 3.2.3 on 2021-10-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0002_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='excerpt',
            name='genre',
            field=models.CharField(default='Fiction', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='excerpt_date',
            field=models.CharField(max_length=64),
        ),
    ]
