# Generated by Django 3.2.3 on 2021-10-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0003_auto_20211003_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excerpt',
            old_name='exerpt_text',
            new_name='excerpt_text',
        ),
    ]
