# Generated by Django 3.2.3 on 2022-02-13 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0004_rename_exerpt_text_excerpt_excerpt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.CharField(max_length=64)),
                ('reward_book', models.CharField(max_length=64)),
                ('reward_author', models.CharField(max_length=64)),
                ('reward_sent', models.BooleanField(default=False)),
                ('user_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreward', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
