# Generated by Django 3.2.3 on 2022-03-12 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0005_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_topbook', models.CharField(max_length=64)),
                ('author_topbook', models.CharField(max_length=64)),
                ('user_topbook', models.ManyToManyField(related_name='usertopbook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
