# Generated by Django 3.2.3 on 2022-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0007_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_book',
            field=models.CharField(default='No book', max_length=64),
        ),
    ]
