# Generated by Django 3.2.3 on 2022-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0008_alter_reward_reward_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_book',
            field=models.CharField(max_length=64),
        ),
    ]
